import PDFDocument from "pdfkit";
import { formatCurrency, formatDateTime } from "@/lib/utils";

type ReceiptData = {
  accountNumber: string;
  customerName: string;
  transactionId: string;
  reference: string;
  type: "DEPOSIT" | "WITHDRAWAL";
  amount: number;
  oldBalance: number;
  newBalance: number;
  createdAt: Date;
};

export async function buildReceiptPdf(data: ReceiptData) {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 110).fill("#13243d");
    doc.fillColor("#ffffff").fontSize(24).text("TrustBank Transaction Receipt", 40, 40);
    doc.fontSize(11).text("Secure Evidence Copy", 40, 76);

    doc.fillColor("#13243d").fontSize(12);
    doc.text(`Customer: ${data.customerName}`, 40, 145);
    doc.text(`Account: ${data.accountNumber}`, 40, 168);
    doc.text(`Transaction ID: ${data.transactionId}`, 40, 191);
    doc.text(`Reference: ${data.reference}`, 40, 214);
    doc.text(`Date: ${formatDateTime(data.createdAt)}`, 40, 237);

    doc.roundedRect(40, 285, 515, 130, 12).stroke("#c58a31");
    doc.fontSize(15).text(`${data.type} SUMMARY`, 58, 305);
    doc.fontSize(12);
    doc.text(`Amount: ${formatCurrency(data.amount)}`, 58, 338);
    doc.text(`Previous Balance: ${formatCurrency(data.oldBalance)}`, 58, 362);
    doc.text(`New Balance: ${formatCurrency(data.newBalance)}`, 58, 386);

    doc.fontSize(10).fillColor("#5e6d7e");
    doc.text(
      "This receipt was generated by the Bank Document & Transaction Evidence Storage System and stored in Azure Blob Storage with private access controls.",
      40,
      470,
      { width: 515 }
    );

    doc.end();
  });
}
